version: "3.9"

services:
  main:
    image: "modoth/udev:latest"
    stdin_open: true
    tty: true
    environment:
      - "LANG=C.UTF-8"
    volumes:
      - "./libs/main:/home/dev/.commons/main"
      - "./Projects:/home/dev/Projects"
    restart: always
    container_name: template.dev
    hostname: template.dev

