#!/usr/bin/env zsh
if [ -f '/etc/sudoers.d/dev_install_tmp' ];then
    sudo zsh /bin/run_install && sudo rm '/etc/sudoers.d/dev_install_tmp'
fi

start="/home/dev/.commons/main/start"
if [ -f "$start" ];then
  exec zsh "$start"
else
  exec zsh
fi
